// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tfInit
void tfInit();
RcppExport SEXP TensorFlow_tfInit() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    tfInit();
    return R_NilValue;
END_RCPP
}
