# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Initialize the library
#'
#' Initialize the library
#'
#' @export
#'
tfInit <- function() {
    invisible(.Call('TensorFlow_tfInit', PACKAGE = 'TensorFlow'))
}

